spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: username
      password: password
      database: customer
      authentication-database: admin
server:
  port: 8090
